name: Repository Languages and CodeQL Support Map
author: Austen Stone / Lucas Ventura
description: List a repository languages using the GitHub API and filter by CodeQL support
branding:
  icon: "list"
  color: "blue"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  owner:
    description: The owner of the repository
    default: ${{ github.repository_owner }}
    required: false
  repo:
    description: The name of the repository
    default: ${{ github.event.repository.name }}
    required: false

outputs:
  languages:
    description: The languages of the repository as a JSON array
  languages_codeql:
    description: The languages of the repository with CodeQL support as a JSON array, already formatted in the name that is identified by codeql

runs:
  using: "node20"
  main: "dist/index.js"
