name: Repository Languages and CodeQL Support Map
author: Lucas Ventura / Austen Stone
description: List a repository languages using the GitHub API and filter by CodeQL support
branding:
  icon: "list"
  color: "blue"

inputs:
  github_token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  owner:
    description: The owner of the repository
    default: ${{ github.repository_owner }}
    required: false
  repo:
    description: The name of the repository
    default: ${{ github.event.repository.name }}
    required: false
  buildvpn_cpp:
    description: The build for C/C++ projects needs VPN Connection
    default: false
    required: false
    type: boolean
  buildvpn_csharp:
    description: The build for C# projects needs VPN Connection
    default: false
    required: false
    type: boolean
  buildvpn_go:
    description: The build for Go projects needs VPN Connection
    default: false
    required: false
    type: boolean
  buildvpn_javakotlin:
    description: The build for Java projects needs VPN Connection
    default: false
    required: false
    type: boolean
  buildvpn_js:
    description: The build for javascript-typescript projects needs VPN Connection
    default: false
    required: false
    type: boolean
  buildvpn_python:
    description: The build for Python projects needs VPN Connection
    default: false
    required: false
    type: boolean
  buildvpn_ruby:
    description: The build for Ruby projects needs VPN Connection
    default: false
    required: false
    type: boolean
  buildvpn_swift:
    description: The build for Swift projects needs VPN Connection
    default: false
    required: false
    type: boolean
  buildmode_cpp:
    description: The build mode for C/C++ projects
    required: false
  buildmode_csharp:
    description: The build mode for C# projects
    required: false
  buildmode_go:
    description: The build mode for Go projects
    required: false
  buildmode_javakotlin:
    description: The build mode for Java projects
    required: false
  buildmode_js:
    description: The build mode for javascript-typescript projects
    required: false
  buildmode_python:
    description: The build mode for Python projects
    required: false
  buildmode_ruby:
    description: The build mode for Ruby projects
    required: false
  buildmode_swift:
    description: The build mode for Swift projects
    required: false
  buildmode_manual_cpp:
    description: The command to build cpp projects when build mode is set to manual
    required: false
  buildmode_manual_csharp:
    description: The command to build csharp projects when build mode is set to manual
    required: false
  buildmode_manual_go:
    description: The command to build go projects when build mode is set to manual
    required: false
  buildmode_manual_javakotlin:
    description: The command to build java projects when build mode is set to manual
    required: false
  buildmode_manual_js:
    description: The command to build javascript-typescript projects when build mode is set to manual
    required: false
  buildmode_manual_python:
    description: The command to build python projects when build mode is set to manual
    required: false
  buildmode_manual_ruby:
    description: The command to build ruby projects when build mode is set to manual
    required: false
  buildmode_manual_swift:
    description: The command to build swift projects when build mode is set to manual
    required: false
  precommands_cpp:
    description: The pre-commands to run before building cpp projects
    required: false
  precommands_csharp:
    description: The pre-commands to run before building csharp projects
    required: false
  precommands_go:
    description: The pre-commands to run before building go projects
    required: false
  precommands_javakotlin:
    description: The pre-commands to run before building java projects
    required: false
  precommands_js:
    description: The pre-commands to run before building javascript-typescript projects
    required: false
  precommands_python:
    description: The pre-commands to run before building python projects
    required: false
  precommands_ruby:
    description: The pre-commands to run before building ruby projects
    required: false
  precommands_swift:
    description: The pre-commands to run before building swift projects
    required: false
  envvars_cpp:
    description: The environment variables to set before building cpp projects
    required: false
  envvars_csharp:
    description: The environment variables to set before building csharp projects
    required: false
  envvars_go:
    description: The environment variables to set before building go projects
    required: false
  envvars_javakotlin:
    description: The environment variables to set before building java projects
    required: false
  envvars_js:
    description: The environment variables to set before building javascript-typescript projects
    required: false
  envvars_python:
    description: The environment variables to set before building python projects
    required: false
  envvars_ruby:
    description: The environment variables to set before building ruby projects
    required: false
  envvars_swift:
    description: The environment variables to set before building swift projects
    required: false
  skip_languages:
    description: The languages to skip when building the languages map, comma separated list
    required: false

outputs:
  languages_repo:
    description: The languages of the repository as a JSON array
  languages_codeql:
    description: The languages of the repository with CodeQL support as a JSON array, already formatted in the name that is identified by codeql
  languages_codeql_w_buildmode:
    description: The languages of the repository with CodeQL support as a JSON array, already formatted in the name that is identified by codeql and the build mode
  codeql_supported:
    description: Bool that indicates if there are supported languages by CodeQL 
  skip_languages:
    description: The languages that were skipped when building the languages map

runs:
  using: "node20"
  main: "dist/index.js"
