name: Print Languages
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: list-languages
      - run: |
          echo "Languages Repo: ${{ steps.list-languages.outputs.languages_repo }}"
          echo "Languages CodeQL: ${{ steps.list-languages.outputs.languages_codeql }}"
          echo "Languages CodeQL With BuildMode: ${{ steps.list-languages.outputs.languages_codeql_w_buildmode }}"
          echo "CodeQL Supported: ${{ steps.list-languages.outputs.codeql_supported }}"